# .github/workflows/python-package.yml
name: Python Package CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package & test tools
        run: |
          python -m pip install --upgrade pip
          # install your library itself
          pip install -e .
          # install pytest and flake8
          pip install pytest flake8

      - name: Lint with flake8
        run: flake8 src

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q
